import {VirtualFS} from './VirtualFS.js';import {ProcessManager} from './ProcessManager.js';import {Scheduler} from './Scheduler.js';import {SyscallAPI} from './Syscalls.js';import {initializeFilesystem} from './FilesystemLayout.js';import {ProcessMemory} from './ProcessMemory.js';import {ProgramLoader} from './ProgramLoader.js';import {VirtualMemoryManager} from '../memory/VirtualMemoryManager.js';import {KernelMemory} from '../memory/KernelMemory.js';import {launchInit} from './InitProcess.js';
export class Kernel {constructor(machine,fs=null){this.machine=machine;this.fs=fs||new VirtualFS();this.vmm=new VirtualMemoryManager(machine.ram);this.processes=new ProcessManager(this);this.scheduler=new Scheduler();this.current=null;this.syscalls=new SyscallAPI(this);this.gui=null;this.booted=false;this.programLoader=new ProgramLoader(this);this.kernelMemory=new KernelMemory(this.vmm);this.lastFault=null;}
 async boot(){await this.fs.ensureReady();await initializeFilesystem(this.fs);await this.fs.writeFile('/proc/version','VCPU-64 kernel 0.8');await this.fs.writeFile('/proc/arch','VCPU-64');await this.fs.writeFile('/proc/meminfo',JSON.stringify(this.vmm.stats()));this.booted=true;try{const init=await launchInit(this);this.scheduler.add(init);}catch(e){this.lastFault=e;this.write(`[ kernel ] init failed: ${e.message}\n`);}return this.fs.readFile('/etc/motd');}
 write(text){for(const c of String(text))this.machine.terminal.write(c.charCodeAt(0));return String(text).length;}read(){return this.machine.terminal.read();}
 spawn(entry=0x1000,name='process'){const p=this.processes.create(entry,name,null);p.memory=new ProcessMemory(this.vmm,p);p.memory.map(0x1000,0x100000,'rw-',true);p.memory.map(0x7F0000,0x10000,'rw-',true);p.sp=0x7FFFF0;return p.pid;}
 async spawnAssembly(path,name=path){const pid=await this.programLoader.loadFile(path,{origin:0x1000,name});const p=this.processes.get(pid);this.scheduler.add(p);return p;}
 attachProcessCPU(p){if(!p.cpu){const C=this.machine.cpu.constructor;p.cpu=new C({mmu:this.vmm,ram:this.machine.ram,terminal:this.machine.terminal,gpu:this.machine.gpu,syscall:(n,cpu)=>{const result=this.syscalls.call(n,[...cpu.reg]);if(result!==undefined)cpu.reg[0]=BigInt(result);}});}p.attachCPU(p.cpu);this.vmm.use(p.memory.space);p.cpu.mmu=this.vmm;p.cpu.mode=1;}
 detachProcessCPU(){this.vmm.use(null);this.machine.cpu.mode=0;}
 exit(code=0){if(this.current)this.processes.kill(this.current.pid,code);return code;}
 handleFault(process,error){this.lastFault={pid:process.pid,name:process.name,error};this.write(`\n[ kernel ] ${process.name}[${process.pid}] fault: ${error.message}\n`);this.processes.crash(process.pid,error);this.scheduler.remove(process);this.current=null;}
 schedule(){if(this.current?.cpu)this.current.saveCPU();this.detachProcessCPU();this.current=this.scheduler.next();if(this.current)this.attachProcessCPU(this.current);return this.current;}
 tick(cycles=2000){if(!this.booted)return;let p=this.current;if(!p||p.state!=='running')p=this.schedule();if(!p)return;try{this.attachProcessCPU(p);p.cpu.run(cycles);p.saveCPU();if(p.cpu.halted&&p.state==='running')this.processes.kill(p.pid,0);}catch(e){this.handleFault(p,e);}if(this.scheduler.consume(cycles))this.schedule();this.processes.reap();}
 memoryStats(){return this.vmm.stats();}
 diagnostics(){return{booted:this.booted,currentPid:this.current?.pid??null,processes:this.processes.list().map(p=>({pid:p.pid,name:p.name,state:p.state,pc:p.pc,sp:p.sp,fault:p.fault?.message??null})),scheduler:this.scheduler.snapshot(),memory:this.vmm.stats(),lastFault:this.lastFault};}
}