import {OPCODES,OPCODE_NAMES} from './opcodes.js';import {createFlags} from './flags.js';import {MEMORY_MAP} from '../memory/memoryMap.js';import {MODES} from './privilege.js';
const U64=0xFFFFFFFFFFFFFFFFn;
export class CPU{
 constructor({mmu=null,ram=null,terminal=null,gpu=null,syscall=null}={}){this.mmu=mmu;this.ram=ram;this.terminal=terminal;this.gpu=gpu;this.syscall=syscall;this.reg=Array.from({length:16},()=>0n);this.flags=createFlags();this.pc=MEMORY_MAP.PROGRAM_START;this.sp=MEMORY_MAP.STACK_TOP;this.halted=true;this.cycles=0;this.lastInstruction='';this.mode=MODES.KERNEL;this.interruptsEnabled=true;this.inInterrupt=false;this.currentPid=0;}
 reset(){this.reg.fill(0n);this.flags=createFlags();this.pc=MEMORY_MAP.PROGRAM_START;this.sp=MEMORY_MAP.STACK_TOP;this.halted=true;this.cycles=0;this.lastInstruction='';this.mode=MODES.KERNEL;this.interruptsEnabled=true;this.inInterrupt=false;this.currentPid=0;}
 u(v){return BigInt.asUintN(64,BigInt(v));}s(v){return BigInt.asIntN(64,this.u(v));}
 read8(a){return this.mmu?this.mmu.read8(a):a===MEMORY_MAP.TERMINAL_IN?(this.terminal?.read()??0):this.ram.read8(a);}write8(a,v){if(this.mmu){this.mmu.write8(a,v);return;}if(a===MEMORY_MAP.TERMINAL_OUT){this.terminal?.write(v);return;}this.ram.write8(a,v);}
 read16(a){return this.read8(a)|this.read8(a+1)<<8;}write16(a,v){this.write8(a,v);this.write8(a+1,v>>8);}
 read64(a){let v=0n;for(let i=0;i<8;i++)v|=BigInt(this.read8(Number(a)+i))<<(8n*BigInt(i));return v;}write64(a,v){v=this.u(v);for(let i=0;i<8;i++)this.write8(Number(a)+i,Number((v>>(8n*BigInt(i)))&255n));}
 fetch8(){const v=this.read8(this.pc);this.pc=(this.pc+1)&0xFFFF;return v;}fetch16(){const v=this.read16(this.pc);this.pc=(this.pc+2)&0xFFFF;return v;}
 fetch64(){const v=this.read64(this.pc);this.pc=(this.pc+8)&0xFFFF;return v;}
 push(v){this.sp=(this.sp-8)&0xFFFF;this.write64(this.sp,v);}pop(){const v=this.read64(this.sp);this.sp=(this.sp+8)&0xFFFF;return v;}
 setFlags(v,carry=false){v=this.u(v);this.flags.Z=v===0n;this.flags.N=!!(v&0x8000000000000000n);this.flags.C=carry;}
 operand(){const mode=this.fetch8();if(mode<16)return{mode:'reg',index:mode,value:this.reg[mode]};if(mode===0x80)return{mode:'imm',value:this.fetch64()};if(mode===0x40)return{mode:'mem',address:Number(this.fetch64()),value:0n};throw new Error('Invalid operand mode 0x'+mode.toString(16));}
 readOperand(o){return o.mode==='reg'?this.reg[o.index]:o.mode==='imm'?o.value:this.read64(o.address);}writeOperand(o,v){v=this.u(v);if(o.mode==='reg')this.reg[o.index]=v;else if(o.mode==='mem')this.write64(o.address,v);else throw new Error('Cannot write immediate');}
 enterInterrupt(vector,returnPc=this.pc){if(!this.interruptsEnabled)return false;this.push(this.flagsToWord());this.push(this.mode);this.push(BigInt(returnPc));this.mode=MODES.KERNEL;this.interruptsEnabled=false;this.inInterrupt=true;this.pc=(0x20+(vector&0xFF)*8)&0xFFFF;return true;}
 iret(){this.pc=Number(this.pop());this.mode=Number(this.pop())&1;this.wordToFlags(this.pop());this.interruptsEnabled=true;this.inInterrupt=false;}
 flagsToWord(){return BigInt((this.flags.Z?1:0)|(this.flags.N?2:0)|(this.flags.C?4:0)|(this.flags.V?8:0));}wordToFlags(v){v=Number(v);this.flags.Z=!!(v&1);this.flags.N=!!(v&2);this.flags.C=!!(v&4);this.flags.V=!!(v&8);}
 step(){if(this.halted)return;const opcode=this.fetch8();this.lastInstruction=OPCODE_NAMES[opcode]??'???';switch(opcode){
 case OPCODES.NOP:break;case OPCODES.HALT:this.halted=true;break;
 case OPCODES.MOV:{const d=this.operand(),s=this.operand();this.writeOperand(d,this.readOperand(s));break;}case OPCODES.LOAD:{const d=this.operand(),a=this.operand();this.writeOperand(d,this.read64(Number(this.readOperand(a))));break;}case OPCODES.STORE:{const a=this.operand(),s=this.operand();this.write64(Number(this.readOperand(a)),this.readOperand(s));break;}
 case OPCODES.PUSH:this.push(this.readOperand(this.operand()));break;case OPCODES.POP:this.writeOperand(this.operand(),this.pop());break;
 case OPCODES.ADD:{const d=this.operand(),s=this.operand(),a=this.readOperand(d),b=this.readOperand(s),r=a+b;this.writeOperand(d,r);this.setFlags(r,r>U64);break;}case OPCODES.SUB:{const d=this.operand(),s=this.operand(),a=this.readOperand(d),b=this.readOperand(s),r=a-b;this.writeOperand(d,r);this.setFlags(r,a<b);break;}case OPCODES.MUL:{const d=this.operand(),s=this.operand(),r=this.readOperand(d)*this.readOperand(s);this.writeOperand(d,r);this.setFlags(r,r>U64);break;}case OPCODES.DIV:{const d=this.operand(),s=this.operand(),b=this.readOperand(s);if(!b)throw new Error('Division by zero');const r=this.readOperand(d)/b;this.writeOperand(d,r);this.setFlags(r);break;}case OPCODES.MOD:{const d=this.operand(),s=this.operand(),b=this.readOperand(s);if(!b)throw new Error('Division by zero');const r=this.readOperand(d)%b;this.writeOperand(d,r);this.setFlags(r);break;}
 case OPCODES.INC:{const d=this.operand(),r=this.readOperand(d)+1n;this.writeOperand(d,r);this.setFlags(r);break;}case OPCODES.DEC:{const d=this.operand(),r=this.readOperand(d)-1n;this.writeOperand(d,r);this.setFlags(r);break;}case OPCODES.NEG:{const d=this.operand(),r=-this.readOperand(d);this.writeOperand(d,r);this.setFlags(r);break;}
 case OPCODES.AND:case OPCODES.OR:case OPCODES.XOR:{const d=this.operand(),s=this.operand(),a=this.readOperand(d),b=this.readOperand(s);const r=opcode===OPCODES.AND?a&b:opcode===OPCODES.OR?a|b:a^b;this.writeOperand(d,r);this.setFlags(r);break;}case OPCODES.NOT:{const d=this.operand(),r=~this.readOperand(d);this.writeOperand(d,r);this.setFlags(r);break;}
 case OPCODES.CMP:{const a=this.readOperand(this.operand()),b=this.readOperand(this.operand()),r=a-b;this.setFlags(r,a<b);break;}
 case OPCODES.JMP:this.pc=this.fetch16();break;case OPCODES.JZ:{const a=this.fetch16();if(this.flags.Z)this.pc=a;break;}case OPCODES.JNZ:{const a=this.fetch16();if(!this.flags.Z)this.pc=a;break;}case OPCODES.JC:{const a=this.fetch16();if(this.flags.C)this.pc=a;break;}case OPCODES.JNC:{const a=this.fetch16();if(!this.flags.C)this.pc=a;break;}case OPCODES.JN:{const a=this.fetch16();if(this.flags.N)this.pc=a;break;}case OPCODES.JP:{const a=this.fetch16();if(!this.flags.N)this.pc=a;break;}case OPCODES.JO:{const a=this.fetch16();if(this.flags.V)this.pc=a;break;}case OPCODES.JNP:{const a=this.fetch16();if(this.flags.N)this.pc=a;break;}
 case OPCODES.CALL:{const a=this.fetch16();this.push(BigInt(this.pc));this.pc=a;break;}case OPCODES.RET:this.pc=Number(this.pop());break;
 case OPCODES.SHL:{const d=this.operand(),s=this.operand(),r=this.readOperand(d)<<(this.readOperand(s)&63n);this.writeOperand(d,r);this.setFlags(r);break;}case OPCODES.SHR:{const d=this.operand(),s=this.operand(),r=this.readOperand(d)>>(this.readOperand(s)&63n);this.writeOperand(d,r);this.setFlags(r);break;}case OPCODES.SAR:{const d=this.operand(),s=this.operand(),r=this.u(this.s(this.readOperand(d))>>(this.readOperand(s)&63n));this.writeOperand(d,r);this.setFlags(r);break;}case OPCODES.ROL:{const d=this.operand(),s=this.operand(),n=this.readOperand(s)&63n,a=this.readOperand(d),r=n?this.u((a<<n)|(a>>(64n-n))):a;this.writeOperand(d,r);this.setFlags(r);break;}case OPCODES.ROR:{const d=this.operand(),s=this.operand(),n=this.readOperand(s)&63n,a=this.readOperand(d),r=n?this.u((a>>n)|(a<<(64n-n))):a;this.writeOperand(d,r);this.setFlags(r);break;}
 case OPCODES.OUT:this.terminal?.write(Number(this.readOperand(this.operand())&255n));break;case OPCODES.IN:this.writeOperand(this.operand(),BigInt(this.terminal?.read()??0));break;case OPCODES.INT:this.enterInterrupt(this.fetch8());break;case OPCODES.IRET:this.iret();break;case OPCODES.CLI:this.interruptsEnabled=false;break;case OPCODES.STI:this.interruptsEnabled=true;break;
 case OPCODES.PIXEL:{const x=Number(this.readOperand(this.operand())),y=Number(this.readOperand(this.operand())),c=Number(this.readOperand(this.operand()));this.gpu?.pixel(x,y,c);break;}case OPCODES.RECT:{const x=Number(this.readOperand(this.operand())),y=Number(this.readOperand(this.operand())),w=Number(this.readOperand(this.operand())),h=Number(this.readOperand(this.operand())),c=Number(this.readOperand(this.operand()));this.gpu?.rect(x,y,w,h,c);break;}case OPCODES.GPUCLEAR:{this.gpu?.clear(Number(this.readOperand(this.operand())));break;}case OPCODES.SYSCALL:{const n=Number(this.readOperand(this.operand()));this.syscall?.(n,this);break;}
 default:throw new Error('Illegal opcode 0x'+opcode.toString(16));}this.cycles++;}
 run(maxCycles=100000){this.halted=false;let n=0;while(!this.halted&&n++<maxCycles)this.step();if(n>=maxCycles){this.halted=true;throw new Error('Execution limit reached');}}
}