import {OPCODES} from '../cpu/opcodes.js';
const reg=/^R([0-9]|1[0-5])$/i;
const branch=new Set(['JMP','JZ','JNZ','JC','JNC','JN','JP','JO','JNP','CALL']);
function isRegister(s){return reg.test(s.trim());}
function parseNumber(s,labels){s=s.trim();if(isRegister(s))throw new Error('Register is not a number: '+s);if(Object.prototype.hasOwnProperty.call(labels,s))return labels[s];if(/^0x[\da-f]+$/i.test(s))return Number.parseInt(s,16);if(/^0b[01]+$/i.test(s))return Number.parseInt(s.slice(2),2);if(/^-?\d+$/.test(s))return Number(s);throw new Error('Unknown symbol: '+s);}
function splitArgs(s){const out=[];let cur='',depth=0,q=null;for(const c of s){if((c==='"'||c==="'")&&(q===null||q===c)){q=q===c?null:q||c;cur+=c;continue;}if(!q&&c==='[')depth++;if(!q&&c===']')depth--;if(!q&&depth===0&&c===','){out.push(cur.trim());cur='';}else cur+=c;}if(cur.trim())out.push(cur.trim());return out;}
function parseLine(raw){let line=raw.replace(/;.*$/,'').trim();if(!line)return null;let label=null;const m=line.match(/^([A-Za-z_]\w*):/);if(m){label=m[1];line=line.slice(m[0].length).trim();}if(!line)return{label,op:null,args:[]};const x=line.match(/^([A-Za-z]+)\s*(.*)$/);return{label,op:x[1].toUpperCase(),args:splitArgs(x[2])};}
function dataBytes(args,labels){const out=[];for(const s of args){if(/^['"].*['"]$/.test(s)){const t=s.slice(1,-1);for(let i=0;i<t.length;i++){if(t[i]==='\\'&&i+1<t.length){const c=t[++i];out.push(c==='n'?10:c==='r'?13:c==='t'?9:c.charCodeAt(0));}else out.push(t.charCodeAt(i)&255);}}else out.push(parseNumber(s,labels)&255);}return out;}
function operandSize(s){return isRegister(s)?1:9;}
export function assemble(source,{origin=0x1000}={}){const lines=String(source).split(/\r?\n/).map(parseLine),labels={};let pc=origin;for(const l of lines){if(!l)continue;if(l.label)labels[l.label]=pc;if(!l.op)continue;if(l.op==='DB'){pc+=dataBytes(l.args,labels).length;continue;}if(OPCODES[l.op]===undefined)throw new Error('Unknown instruction: '+l.op);if(['NOP','HALT','RET','IRET','CLI','STI'].includes(l.op))pc++;else if(branch.has(l.op))pc+=l.op==='INT'?2:3;else if(l.op==='INT')pc+=2;else if(['PUSH','POP','INC','DEC','NOT','NEG','OUT','IN','SYSCALL','GPUCLEAR'].includes(l.op))pc+=1+operandSize(l.args[0]);else pc+=1+l.args.reduce((n,a)=>n+operandSize(a),0);}
 const out=[];const e8=v=>out.push(Number(v)&255);const e16=v=>{e8(v);e8(Number(v)>>8);};const e64=v=>{v=BigInt.asUintN(64,BigInt(v));for(let i=0;i<8;i++)e8(Number((v>>BigInt(i*8))&255n));};const operand=t=>{t=t.trim();const r=t.match(reg);if(r){e8(Number(r[1]));return;}const m=t.match(/^\[(.+)\]$/);if(m){e8(0x40);e64(parseNumber(m[1],labels));return;}e8(0x80);e64(parseNumber(t,labels));};
 for(const l of lines){if(!l||!l.op)continue;if(l.op==='DB'){dataBytes(l.args,labels).forEach(e8);continue;}e8(OPCODES[l.op]);if(['NOP','HALT','RET','IRET','CLI','STI'].includes(l.op))continue;if(branch.has(l.op)){e16(parseNumber(l.args[0],labels));continue;}if(l.op==='INT'){e8(parseNumber(l.args[0],labels));continue;}l.args.forEach(operand);}return{bytes:new Uint8Array(out),labels,origin};}
export const assembleProgram=assemble;